import React from 'react';

export interface CouponItem {
  id?: number; // Optional, as it may be generated by IndexedDB
  name: string;
  dealValue: string;
  expirationDate?: Date | null;
  onClick?: () => void; 
}

const Coupon: React.FC<CouponItem> = (coupon: CouponItem) => {
  const {name, dealValue, expirationDate, onClick} = coupon;
  return (
    <tr onClick={onClick} style={{ cursor: onClick ? 'pointer' : 'default' }}>
      <td>{name}</td>
      <td>{dealValue}</td>
      <td>{expirationDate?.toString() || 'N/A'}</td>
    </tr>
  );
};

export default Coupon;